### Get all the content
GET http://localhost:8080/api/content

### Get content by Id
GET http://localhost:8080/api/content/1

### Add new content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "My Second Blog Post",
  "desc": "My second blog post",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2025-02-15T14:48:19.9154251",
  "dateUpdated": null,
  "url": ""
}

### Updating existing content
PUT http://localhost:8080/api/content/2
Content-Type: application/json

{
  "id": 2,
  "title": "My Second Blog Post",
  "desc": "My second blog post",
  "status": "IDEA",
  "contentType": "COURSE",
  "dateCreated": "2025-02-15T14:48:19.9154251",
  "dateUpdated": null,
  "url": ""
}